/*
 * Minimal, dependency-free Markdown renderer for the notes tool.
 *
 * Security model (escape-first): the ENTIRE source text is HTML-escaped
 * before any Markdown syntax is turned into tags. Only tags generated by
 * this module ever reach the output – user-supplied "<script>" etc. always
 * arrives as inert "&lt;script&gt;" text.
 *
 * Supported (deliberately small, Obsidian-compatible subset):
 *   headings # ## ###, **bold**, *italic* / _italic_, `inline code`,
 *   ``` code fences ```, unordered (- / *) and ordered (1. / 1)) lists,
 *   [links](https://…), [[wiki-links]], blank-line separated paragraphs.
 */

import { renderMathHtml } from '@cardo/ui';

export function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/** Reverse escapeHtml so LaTeX source (which may contain < > & …) reaches KaTeX intact. */
function unescapeHtml(text: string): string {
  return text
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&amp;/g, '&');
}

/** Allow only harmless link targets; anything like "javascript:…" is rejected. */
function safeHref(rawUrl: string): string | null {
  const url = rawUrl.trim();
  if (/^(https?:|mailto:)/i.test(url)) return url;
  // Any other explicit scheme (javascript:, data:, vbscript:, …) is blocked.
  if (/^[a-z][a-z0-9+.-]*:/i.test(url)) return null;
  // Scheme-less (relative / anchor) targets are inert.
  return url;
}

/**
 * Inline Markdown on an ALREADY-ESCAPED string.
 * Code spans are cut out first (placeholder tokens) so bold/italic/link
 * syntax inside backticks stays literal.
 */
export function renderInline(escaped: string): string {
  const codeSpans: string[] = [];
  // U+E000/U+E001 (private use area) are the placeholder sentinels for code
  // spans and math. Strip any pre-existing occurrence so user text can never
  // forge one.
  let out = escaped
    .replace(/[\uE000\uE001]/g, '')
    .replace(/`([^`]+)`/g, (_m, code: string) => {
      codeSpans.push(code);
      return `\uE000${codeSpans.length - 1}\uE000`;
    });

  // LaTeX math \u2013 cut out (like code spans) so its $, \, {} never collide with
  // the Markdown passes below. Content is un-escaped before KaTeX because it
  // was HTML-escaped upstream. Display $$\u2026$$ first, then inline $\u2026$ (only when
  // it actually looks like math, so prices like "$5" stay literal text).
  const mathSpans: string[] = [];
  const pushMath = (tex: string, display: boolean): string => {
    mathSpans.push(renderMathHtml(unescapeHtml(tex), display));
    return `\uE001${mathSpans.length - 1}\uE001`;
  };
  out = out.replace(/\$\$([^\n]+?)\$\$/g, (_m, tex: string) => pushMath(tex, true));
  out = out.replace(/\$([^\n$]+?)\$/g, (m, tex: string) =>
    /[\\^_{}]/.test(tex) ? pushMath(tex, false) : m,
  );

  // Wiki-links [[Note Name]] → internal anchors the widget resolves on click
  // (Obsidian behavior). Runs on the ALREADY-ESCAPED string and BEFORE the
  // normal link rule so the two bracket syntaxes never clash. The data
  // attribute strips (escaped) quotes so the value can never terminate the
  // attribute or smuggle one into it.
  out = out.replace(/\[\[([^\][]+)\]\]/g, (match, name: string) => {
    const label = name.trim();
    // Also strip '*' and the code-span sentinel so the later bold/italic and
    // code-restore passes can never rewrite the inside of the attribute.
    const target = label.replace(/&quot;|&#39;|["'*\uE000]/g, '').trim();
    if (!target) return match;
    return `<a data-note="${target}" class="md-wikilink">${label}</a>`;
  });

  out = out.replace(/\[([^\]]+)\]\(([^)\s]+)\)/g, (match, label: string, url: string) => {
    const href = safeHref(url);
    if (href === null) return match;
    return `<a href="${href}" target="_blank" rel="noopener noreferrer">${label}</a>`;
  });

  out = out.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');
  out = out.replace(/\*([^*]+)\*/g, '<em>$1</em>');
  out = out.replace(/(^|\s)_([^_]+)_(?=\s|$)/g, '$1<em>$2</em>');

  out = out.replace(
    /\uE000(\d+)\uE000/g,
    (_m, i: string) => `<code>${codeSpans[Number(i)] ?? ''}</code>`,
  );
  // Restore rendered KaTeX last: its markup is trusted (trust:false) and must
  // bypass the escaping applied to everything else.
  return out.replace(/\uE001(\d+)\uE001/g, (_m, i: string) => mathSpans[Number(i)] ?? '');
}

/** Render a full Markdown document to a safe HTML string. */
export function renderMarkdown(source: string): string {
  const lines = source.replace(/\r\n/g, '\n').split('\n');
  const html: string[] = [];
  let paragraph: string[] = [];
  let list: { tag: 'ul' | 'ol'; items: string[] } | null = null;

  const flushParagraph = () => {
    if (paragraph.length === 0) return;
    html.push(`<p>${renderInline(escapeHtml(paragraph.join(' ')))}</p>`);
    paragraph = [];
  };
  const flushList = () => {
    if (!list) return;
    html.push(`<${list.tag}>${list.items.map((i) => `<li>${i}</li>`).join('')}</${list.tag}>`);
    list = null;
  };

  let i = 0;
  while (i < lines.length) {
    const line = lines[i] ?? '';

    // Code fence
    if (/^```/.test(line)) {
      flushParagraph();
      flushList();
      const buffer: string[] = [];
      i += 1;
      while (i < lines.length && !/^```/.test(lines[i] ?? '')) {
        buffer.push(lines[i] ?? '');
        i += 1;
      }
      i += 1; // skip closing fence (or run past end for an unclosed fence)
      html.push(`<pre><code>${escapeHtml(buffer.join('\n'))}</code></pre>`);
      continue;
    }

    // Block math fence: a line that is exactly "$$" opens a display-math block
    // until the next "$$" line (single-line "$$…$$" is handled inline instead).
    if (line.trim() === '$$') {
      flushParagraph();
      flushList();
      const buffer: string[] = [];
      i += 1;
      while (i < lines.length && (lines[i] ?? '').trim() !== '$$') {
        buffer.push(lines[i] ?? '');
        i += 1;
      }
      i += 1; // skip closing fence
      html.push(renderMathHtml(buffer.join('\n'), true));
      continue;
    }

    // Headings # … ###
    const heading = /^(#{1,3})\s+(.*)$/.exec(line);
    if (heading) {
      flushParagraph();
      flushList();
      const level = (heading[1] ?? '#').length;
      html.push(`<h${level}>${renderInline(escapeHtml((heading[2] ?? '').trim()))}</h${level}>`);
      i += 1;
      continue;
    }

    // Unordered list item
    const unordered = /^\s*[-*]\s+(.*)$/.exec(line);
    if (unordered) {
      flushParagraph();
      if (list?.tag !== 'ul') flushList();
      list = list ?? { tag: 'ul', items: [] };
      list.items.push(renderInline(escapeHtml(unordered[1] ?? '')));
      i += 1;
      continue;
    }

    // Ordered list item
    const ordered = /^\s*\d+[.)]\s+(.*)$/.exec(line);
    if (ordered) {
      flushParagraph();
      if (list?.tag !== 'ol') flushList();
      list = list ?? { tag: 'ol', items: [] };
      list.items.push(renderInline(escapeHtml(ordered[1] ?? '')));
      i += 1;
      continue;
    }

    // Blank line = block separator
    if (line.trim() === '') {
      flushParagraph();
      flushList();
      i += 1;
      continue;
    }

    // Plain text line → paragraph (a list ends at the first non-item line)
    flushList();
    paragraph.push(line.trim());
    i += 1;
  }

  flushParagraph();
  flushList();
  return html.join('\n');
}
