/**
 * Anki-class card template renderer. Turns a note type template + a note's
 * field values into the HTML shown on a card side.
 *
 * Supports the template features Anki users rely on:
 *   {{Field}}                 field substitution
 *   {{FrontSide}}             the rendered front (on back templates)
 *   {{#Field}}…{{/Field}}     show block when the field is non-empty
 *   {{^Field}}…{{/Field}}     show block when the field IS empty
 *   {{cloze:Field}}           cloze deletions for the active ordinal
 *   {{text:Field}}            field with HTML stripped
 *   $…$ / $$…$$               LaTeX via KaTeX (@cardo/ui renderMathHtml)
 *
 * Security: the substituted HTML is run through an allowlist sanitizer
 * (scripts, event handlers and dangerous URL schemes are removed). KaTeX
 * output is generated by us and re-inserted AFTER sanitizing via placeholder
 * sentinels, so the sanitizer never strips KaTeX's MathML/markup.
 */

import { renderMathHtml } from '@cardo/ui';

/* ── Cloze ────────────────────────────────────────────────────────────────── */

const CLOZE_RE = /\{\{c(\d+)::([\s\S]*?)\}\}/g;

/** Distinct cloze ordinals present in a field, ascending. One card each. */
export function clozeOrdinals(text: string): number[] {
  const found = new Set<number>();
  for (const m of text.matchAll(CLOZE_RE)) found.add(Number(m[1]));
  return [...found].sort((a, b) => a - b);
}

function splitClozeInner(inner: string): { answer: string; hint: string | null } {
  const parts = inner.split('::');
  if (parts.length >= 2) {
    return { answer: parts.slice(0, -1).join('::'), hint: parts[parts.length - 1]! };
  }
  return { answer: inner, hint: null };
}

/**
 * Render cloze markers for one card. The active ordinal is hidden on the front
 * (`[hint]` or `[...]`) and revealed on the back; every other deletion shows
 * its answer on both sides.
 */
export function renderCloze(text: string, activeOrdinal: number, side: 'front' | 'back'): string {
  return text.replace(CLOZE_RE, (_m, ord: string, inner: string) => {
    const { answer, hint } = splitClozeInner(inner);
    if (Number(ord) !== activeOrdinal) return answer;
    if (side === 'front') {
      return `<span class="cloze">[${hint ? hint : '...'}]</span>`;
    }
    return `<span class="cloze">${answer}</span>`;
  });
}

/* ── Conditionals ─────────────────────────────────────────────────────────── */

const COND_RE = /\{\{([#^])([^{}]+?)\}\}([\s\S]*?)\{\{\/\2\}\}/;

function expandConditionals(tpl: string, fields: Record<string, string>): string {
  let out = tpl;
  let prev: string;
  do {
    prev = out;
    out = out.replace(COND_RE, (_m, kind: string, name: string, inner: string) => {
      const nonEmpty = (fields[name.trim()] ?? '').trim() !== '';
      const show = kind === '#' ? nonEmpty : !nonEmpty;
      return show ? inner : '';
    });
  } while (out !== prev);
  return out;
}

/* ── Field substitution ───────────────────────────────────────────────────── */

function stripHtml(html: string): string {
  return html
    .replace(/<[^>]*>/g, '')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .trim();
}

export interface RenderInput {
  template: string;
  fields: Record<string, string>;
  side: 'front' | 'back';
  /** Rendered front HTML, substituted for {{FrontSide}} on back templates. */
  frontSide?: string;
  /** 1-based cloze ordinal for cloze note types; omit for basic notes. */
  clozeOrdinal?: number;
}

/** Substitute template markers (no math, no sanitizing yet). */
export function substitute(input: RenderInput): string {
  const { fields, side, frontSide = '', clozeOrdinal } = input;
  let out = expandConditionals(input.template, fields);

  out = out.replace(/\{\{FrontSide\}\}/g, frontSide);

  out = out.replace(/\{\{cloze:([^{}]+?)\}\}/g, (_m, name: string) => {
    const value = fields[name.trim()] ?? '';
    return clozeOrdinal ? renderCloze(value, clozeOrdinal, side) : value;
  });

  out = out.replace(/\{\{text:([^{}]+?)\}\}/g, (_m, name: string) =>
    stripHtml(fields[name.trim()] ?? ''),
  );

  // Generic {{Field}} – names without a filter colon or block marker.
  out = out.replace(/\{\{([^:{}#^/][^:{}]*?)\}\}/g, (_m, name: string) => fields[name.trim()] ?? '');

  return out;
}

/* ── Anki / MathJax math delimiters → $…$ / $$…$$ ─────────────────────────── */

/**
 * Strip the HTML an Anki editor sprinkles inside a formula (tags, `&nbsp;`,
 * escaped entities) so KaTeX gets clean TeX — otherwise `&nbsp;` alone makes it
 * throw a parse error and render a red error box.
 */
function cleanMath(x: string): string {
  return x
    .replace(/<br\s*\/?>/gi, ' ')
    .replace(/<[^>]+>/g, ' ')
    .replace(/&nbsp;/gi, ' ')
    .replace(/&lt;/gi, '<')
    .replace(/&gt;/gi, '>')
    .replace(/&quot;/gi, '"')
    .replace(/&amp;/gi, '&')
    .trim();
}

/**
 * Anki fields carry math in several delimiter styles; normalise them to the
 * `$…$` (inline) / `$$…$$` (display) forms extractMath understands, so imported
 * cards render as maths instead of showing raw `[latex]…[/latex]` / `[$]…[$]`
 * brackets (or a red KaTeX error) around the formula. Both the slash-closed
 * (`[$]…[/$]`) and the same-delimiter (`[$]…[$]`) Anki forms are supported.
 */
export function convertAnkiMath(html: string): string {
  const inline = (x: string): string => `$${cleanMath(x)}$`;
  const block = (x: string): string => `$$${cleanMath(x)}$$`;
  return html
    .replace(/\[latex\]([\s\S]*?)\[\/latex\]/gi, (_m, x: string) => block(x))
    // Slash-closed forms first, so they are consumed before the same-delimiter
    // patterns can mis-pair across them.
    .replace(/\[\$\$\]([\s\S]*?)\[\/\$\$\]/g, (_m, x: string) => block(x))
    .replace(/\[\$\]([\s\S]*?)\[\/\$\]/g, (_m, x: string) => inline(x))
    // Same-delimiter forms: [$$]…[$$] and [$]…[$].
    .replace(/\[\$\$\]([\s\S]*?)\[\$\$\]/g, (_m, x: string) => block(x))
    .replace(/\[\$\]([\s\S]*?)\[\$\]/g, (_m, x: string) => inline(x))
    .replace(/\\\[([\s\S]*?)\\\]/g, (_m, x: string) => block(x))
    .replace(/\\\(([\s\S]*?)\\\)/g, (_m, x: string) => inline(x));
}

/* ── Math (protected from the sanitizer via sentinels) ────────────────────── */

// U+E001 (private use area) marks where trusted KaTeX output is re-inserted;
// user text can never forge one because extractMath strips it first.
const MATH_SENTINEL = String.fromCharCode(0xe001);

function extractMath(html: string, store: string[]): string {
  let out = html.split(MATH_SENTINEL).join('');
  const push = (tex: string, display: boolean): string => {
    store.push(renderMathHtml(tex, display));
    return `${MATH_SENTINEL}${store.length - 1}${MATH_SENTINEL}`;
  };
  out = out.replace(/\$\$([^\n]+?)\$\$/g, (_m, tex: string) => push(tex, true));
  // Inline $…$ only when it actually looks like math (so "$5" stays literal).
  out = out.replace(/\$([^\n$]+?)\$/g, (m, tex: string) =>
    /[\\^_{}]/.test(tex) ? push(tex, false) : m,
  );
  return out;
}

/* ── Sanitizer (allowlist) ────────────────────────────────────────────────── */

const ALLOWED_TAGS = new Set([
  'a', 'abbr', 'b', 'big', 'blockquote', 'br', 'center', 'code', 'div', 'em',
  'figcaption', 'figure', 'font', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'hr', 'i',
  'img', 'li', 'mark', 'ol', 'p', 'pre', 's', 'small', 'span', 'strong', 'sub',
  'sup', 'table', 'tbody', 'td', 'tfoot', 'th', 'thead', 'tr', 'u', 'ul', 'wbr',
]);
const DANGEROUS_TAGS = new Set([
  'script', 'style', 'iframe', 'object', 'embed', 'link', 'meta', 'base',
  'form', 'input', 'button', 'textarea', 'select', 'svg', 'math',
]);
const ALLOWED_ATTRS = new Set([
  'class', 'id', 'style', 'src', 'alt', 'width', 'height', 'colspan', 'rowspan',
  'href', 'title', 'dir', 'lang', 'align', 'valign', 'color', 'face', 'size',
  'border', 'cellpadding', 'cellspacing',
]);

function safeUrl(raw: string, allowDataImage: boolean): string | null {
  const url = raw.trim();
  if (allowDataImage && /^data:image\/(png|jpe?g|gif|webp|svg\+xml);/i.test(url)) return url;
  if (/^(https?:|mailto:)/i.test(url)) return url;
  if (/^[a-z][a-z0-9+.-]*:/i.test(url)) return null; // javascript:, data:, … blocked
  return url; // scheme-less / relative (Anki media filenames) is inert
}

function scrubElement(el: Element): void {
  for (const attr of [...el.attributes]) {
    const name = attr.name.toLowerCase();
    if (name.startsWith('on') || !ALLOWED_ATTRS.has(name)) {
      el.removeAttribute(attr.name);
      continue;
    }
    if (name === 'href') {
      const safe = safeUrl(attr.value, false);
      if (safe === null) el.removeAttribute(attr.name);
      else el.setAttribute(attr.name, safe);
    } else if (name === 'src') {
      const safe = safeUrl(attr.value, true);
      if (safe === null) el.removeAttribute(attr.name);
      else el.setAttribute(attr.name, safe);
    } else if (name === 'style' && /expression\s*\(|url\s*\(\s*['"]?\s*javascript:/i.test(attr.value)) {
      el.removeAttribute(attr.name);
    }
  }
}

function walk(node: Node): void {
  for (const child of [...node.childNodes]) {
    if (child.nodeType !== 1) continue; // only elements need scrubbing
    const el = child as Element;
    const tag = el.tagName.toLowerCase();
    if (DANGEROUS_TAGS.has(tag)) {
      el.remove();
      continue;
    }
    if (!ALLOWED_TAGS.has(tag)) {
      // Unknown but not dangerous: unwrap, keep the (still-walked) children.
      walk(el);
      const parent = el.parentNode;
      if (parent) {
        while (el.firstChild) parent.insertBefore(el.firstChild, el);
        parent.removeChild(el);
      }
      continue;
    }
    scrubElement(el);
    walk(el);
  }
}

/** Remove scripts, event handlers and dangerous URLs; keep safe formatting. */
export function sanitizeHtml(html: string): string {
  if (typeof DOMParser === 'undefined') {
    // No DOM (plain node): strip all tags as a safe fallback.
    return html.replace(/<[^>]*>/g, '');
  }
  const doc = new DOMParser().parseFromString(html, 'text/html');
  walk(doc.body);
  return doc.body.innerHTML;
}

/* ── Public entry point ───────────────────────────────────────────────────── */

/** Render one card side to sanitized HTML, with math and cloze applied. */
export function renderCard(input: RenderInput): string {
  const substituted = convertAnkiMath(substitute(input));
  const math: string[] = [];
  const withMath = extractMath(substituted, math);
  const sanitized = sanitizeHtml(withMath);
  // Restore trusted KaTeX output at its sentinels (survive as text nodes).
  return sanitized.replace(
    new RegExp(`${MATH_SENTINEL}(\\d+)${MATH_SENTINEL}`, 'g'),
    (_m, i: string) => math[Number(i)] ?? '',
  );
}
